### ISSUE TITLE
Convert .mov to .mp4 video

### ISSUE THREAD

**Issue by oct-test** [madhavanmalolan/ffmpegandroidlibrary#11]
Is it possible to convert to .mov to .mp4 using this library?
Does this library support Android 7.0 and 8.0 devices?

**Comment by madhavanmalolan** [comment]
Absolutely!

**Comment by oct-test** [comment]
Thank you for the reply. I will test it and inform you if I face any issues.

**Comment by oct-test** [comment]
Can please provide the command to covert an .mov video file to .mp4 video file? Sorry, I am completely new to FFMPEG. Thank you.

**Comment by CoXier** [comment]
`ffmpeg -i input.mov output.mp4`.
