### ISSUE TITLE
App crash when converting .mov to .mp4 format

### ISSUE THREAD

**Issue by oct-test** [madhavanmalolan/ffmpegandroidlibrary#12]
I am trying to convert a .mov video file to .mp4 video file using below command:
ffmpeg -i input.mov -c copy output.mp4

But the build crashes with following stack trace:
03-23 14:59:17.864 12242-12242/? I/MultiDex: VM with version 2.1.0 has multidex support
03-23 14:59:17.864 12242-12242/? I/MultiDex: install
03-23 14:59:17.864 12242-12242/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.
03-23 14:59:17.954 12242-12242/? I/Videokit: start run in main.
03-23 14:59:17.954 12242-12242/? I/Videokit: register_exit
03-23 14:59:17.954 12242-12242/? I/Videokit: term_init & parse options.

How can I fix this issue?

**Comment by madhavanmalolan** [comment]
Does your app do only this or are you trying to integrate as a part of a larger project?
Can you also share your build.gradle?

**Comment by oct-test** [comment]
I am integrating this library as part of my larger project. Sorry, I can't share the entire build.gradle file. Can you please tell me the specific portion of the gradle file you want know? Is the command to convert the video file format is correct?

**Comment by madhavanmalolan** [comment]
Looks like you have overshot the maximum number of methods on the android project. You need to enable multidex
https://developer.android.com/studio/build/multidex.html

FFMPEG Command : ffmpeg -i in.mov -vcodec copy -acodec copy out.mp4

**Comment by oct-test** [comment]
I have enabled the multidex support. I have tested the library with this command "ffmpeg -y -i input_file.mov -vcodec copy -an output_file.mov" without any error.

**Comment by madhavanmalolan** [comment]
Awesome! That is nice to know!
Best wishes :+1:

**Comment by oct-test** [comment]
I think you misunderstood my response. Before your suggestion, I already enabled the multidex support. The library is working for muting a video file but when I try to convert the video format, the application crashes.

**Comment by madhavanmalolan** [comment]
Your stacktrace seems to suggest multidex is disabled
` 03-23 14:59:17.864 12242-12242/? I/MultiDex: VM has multidex support, MultiDex support library is disabled.`

Can you check that, you might find some help here
https://stackoverflow.com/questions/33326575/vm-has-multidex-support-multidex-support-library-is-disabled#33327028
