### ISSUE TITLE
buffers as output

### ISSUE THREAD

**Issue by Hosseinyzr** [madhavanmalolan/ffmpegandroidlibrary#14]
Hello,
Actually I have a question that is related to ffmpeg not just to your library.
I wanna output to be saved not in phone disk but in buffers or etc. actually saving in ram I think.
The reason is that I want to process the out put and then reading again is not good in performance.
I have heard about "memory protocol".
I wonder if you know about that?
Thanks.

**Comment by jakibaki** [comment]
Hey, why was this closed?  
It seems to be quite an valid use-case.

If this is out of scope could you please document that?
