### ISSUE TITLE
change mp4 to ts fail

### ISSUE THREAD

**Issue by SunPointed** [madhavanmalolan/ffmpegandroidlibrary#16]
use command like this
```
"-y",
"-i",
"xxx.mp4",
"-vcodec",
"copy",
"-acodec",
"copy",
"test.ts"
```
the test.ts can't play and only 2.2kb(the mp4 is about 10mb),
but when use command like this
```
"-y",
"-i",
"xxx.mp4",
"-vcodec",
"copy",
"-acodec",
"copy",
"test.mp4"
```
it's success.
Can someone give me help, thanks.

**Comment by madhavanmalolan** [comment]
The command is 
`ffmpeg -i input.mp4 -c copy -bsf h264_mp4toannexb output.ts`
