### ISSUE TITLE
Crash when calling 'run()'

### ISSUE THREAD

**Issue by bkatgithub** [madhavanmalolan/ffmpegandroidlibrary#4]
Hi,

I am doing a build based on the instructions in your [blog](https://medium.com/madhavanmalolan/ffmpeg-for-android-b307f2613c82).  When I run it, it crashes when calling 'run(String[])'.  I added some debug statements in the run function and it seems to be in the call to 'main(argc, argv)' in ffmpeg_controller.c.  Logcat has the following messages. Am I missing something in my setup?

`
12-01 21:45:50.306 D: killProcessQuiet, pid=10581
12-01 21:45:50.306 D: com.android.server.am.ActivityManagerService.appDiedLocked:5092 com.android.server.am.ActivityManagerService$AppDeathRecipient.binderDied:1212 android.os.BinderProxy.sendDeathNotice:559 
12-01 21:45:50.306 I: Recipient 10581
12-01 21:45:50.316 W: HtcSystemUPHandler The policy is disabled. AppId: activity_history, category: launch
12-01 21:45:50.316 I: WIN DEATH: Window{2973480c u0 bk.sandbox.ndktest/bk.sandbox.ndktest.MainActivity}
12-01 21:45:50.396 D: Receive mPhoneStateListener
12-01 21:45:50.396 D: Receive mPhoneStateListener, getGsmSignalStrength22
12-01 21:45:50.396 D: onSignalStrengthsChanged
12-01 21:45:50.396 D: processRegCheck. needtoregister: true, mRegistered: false, type: 1, mRtype: 0, Mobile: DISCONNECTED, Wifi: CONNECTED_ROVE_IN, pauseims: DEFAULT
12-01 21:45:50.396 D: doIPServiceUnregistration: Abort: mAtomicDereg.get()=false
12-01 21:45:50.396 D: doIPServiceUnregistration: Abort: mRegistered=false
12-01 21:45:50.396 D: doIPServiceUnregistration: Abort: mAtomicReg.get()=false
12-01 21:45:50.396 D: destroyService. false
12-01 21:45:50.396 D: SignalStrength: 5
12-01 21:45:50.396 D: level=5/5
12-01 21:45:50.426 I: Process bk.sandbox.ndktest (pid 10581) has died
12-01 21:45:50.426 W: Force removing ActivityRecord{1ae37c4f u0 bk.sandbox.ndktest/.MainActivity t27280}: app died, no saved state
`

**Comment by madhavanmalolan** [comment]
Can you share the command you are trying to execute?

**Comment by bkatgithub** [comment]
Thanks.

I added sanityCheck function in ffmpeg_controller.c to return a string to make sure calls are getting to the jni function. And that call works - and I get the return value back in java.  The
call to run() causes the crash.

`
String filesDir = "/storage/sdcard0/Download/";
Controller c = new Controller();

// sanity check to make sure calls are reaching jni funciton.
// This works.
String sanity = c.sanityCheck();
System.err.println("RESPONSE FROM SANITYCHECK: " + sanity);

// call to run() causes a crash
c.run(new String[] {
        "-y",           
        "-i", filesDir + "in.mp4",
        "-vcodec", "copy",
        "-an",          
        filesDir + "out.mp4"
});             

`

**Comment by madhavanmalolan** [comment]
This seems to be a pretty straightforward command. Are you sure you have access to write on the directory you are trying to write on? You would need `android.permission.WRITE_EXTERNAL_STORAGE`
On Android 26, you'd need to get this permission on run time. 

If you already have that permission granted, could you please share the input file you are trying to use?

**Comment by madhavanmalolan** [comment]
Also please use "`Controller.getInstance()`" instead of "`new Controller()`". 
Controller is a singleton class. Using "`new Controller`" doesnot load the FFMPEG libs.

**Comment by bkatgithub** [comment]
Thanks Madhavan! My external write permission was not enabled.  Setting that and changing how Controller is instantiated has helped me get past that issue.  I am able to work with ffmpeg now.
